[package]
name = "zed-fsharp"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zed_extension_api = "0.0.6"
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
