name = "FSharp"
grammar = "fsharp"
code_fence_block_name = "fsharp"
path_suffixes = ["fs", "fsx", "fsi", "fsscript"]
line_comments = ["// "]
lock_comment = ["(* ", "*)"]
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "[|", end = "|", close = true, newline = false },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]